services:
  server:
    build: ./server
    env_file:
      - config/ports.env
      - .env
    ports:
      - "${PHOTOFRAME_SERVER_PORT:-52525}:${PHOTOFRAME_SERVER_PORT:-52525}"
    restart: unless-stopped
